---
- name: Set dev user home
  ansible.builtin.set_fact:
    dev_home: "/home/{{ dev_user }}"

- name: Check for presence of rustup executable
  ansible.builtin.stat:
    path: "{{ dev_home }}/.cargo/bin/rustup"
  register: rustup_exe_status

- name: Download rust Installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: 'yes'
  when: not rustup_exe_status.stat.exists
  tags:
    - rust

- name: Install rust/cargo  # noqa: command-instead-of-shell
  ansible.builtin.shell: /tmp/sh.rustup.rs -y
  args:
    chdir: "{{ dev_home }}"
    creates: "{{ dev_home }}/.cargo/bin/rustup"
  when: not rustup_exe_status.stat.exists
  become: true
  become_user: "{{ dev_user }}"
  tags:
    - rust
