---
common:
  deb_releases:
    cargo_watch:
      name: "cargo-watch"
      release: "https://github.com/watchexec/cargo-watch/releases/download/v8.4.0/cargo-watch-v8.4.0-x86_64-unknown-linux-gnu.deb"
      file: "cargo-watch-v8.4.0-x86_64-unknown-linux-gnu.deb"

    git_delta:
      name: "git-delta"
      release: "https://github.com/dandavison/delta/releases/download/0.16.5/git-delta_0.16.5_amd64.deb"
      file: "git-delta_0.16.5_amd64.deb"

  tar_releases:
    just:
      name: "just"
      release: "https://github.com/casey/just/releases/download/1.14.0/just-1.14.0-x86_64-unknown-linux-musl.tar.gz"
      file: "just-1.14.0-x86_64-unknown-linux-musl.tar.gz"
      target: "just"

    navi:
      name: "navi"
      release: "https://github.com/denisidoro/navi/releases/download/v2.22.1/navi-v2.22.1-x86_64-unknown-linux-musl.tar.gz"
      file: "navi-v2.22.1-x86_64-unknown-linux-musl.tar.gz"
      target: "navi"
