---
- name: Configure dev box nodes
  hosts: dev_box
  become: true
  roles:
    - role: common
    - role: rust
    - role: docker
    - role: dev_box
      become: true
      become_user: "{{ dev_user }}"
