---
build_node:
  hosts:
    dinyol-hei.home:
      start_services: true
      worker_name: dinyol-hei
      worker_tags: "internal,packager,ser6,7735HS"
    ethics-gradient.home:
      start_services: true
      worker_name: ethics-gradient
      worker_tags: "internal,packager,ser6,7735HS"
    little-rascal.home:
      start_services: true
      worker_name: little-rascal
      worker_tags: "internal,packager,eq12,N305"

monitoring:
  hosts:
    monitoring.home:
      start_services: true

pihole:
  hosts:
    sursamen.home:
      start_services: true

probe:
  hosts:
    probe-01.home:
      start_services: true
      zone: office
    probe-03.home:
      start_services: true
      zone: garage
    probe-04.home:
      start_services: true
      zone: master
    # probe-05.home:
    #   start_services: true
    #   zone: kitchen
    probe-05.home:
      start_services: true
      zone: dining
      pep668: true
    probe-06.home:
      start_services: true
      zone: living
      pep668: true

tailscale:
  hosts:
    grey-area.home:
      start_services: true
      name: grey-area

legacy:
  hosts:
    dibaldipen.home:
      start_services: true

dev_box:
  hosts:
    192.168.40.109:
      start_services: true

docker_ci_worker:
  hosts:
    docker-ci-worker-01.home:
      start_services: true
