build_node:
  hosts:
    localhost:
      ansible_connection: local
      worker_name: test-worker
      worker_tags: "testonly"

dev_box:
  hosts:
    localhost:
      ansible_connection: local
      name: test-node

tailscale:
  hosts:
    localhost:
      ansible_connection: local
      name: test-node
