build_node:
  hosts:
    localhost_build_node:
      start_services: false
      ansible_connection: local
      worker_name: test-worker
      worker_tags: "testonly"

docker_ci_worker:
  hosts:
    localhost_docker_ci_worker_node:
      start_services: false
      ansible_connection: local

dev_box:
  hosts:
    localhost_dev_box:
      start_services: false
      ansible_connection: local
      name: test-node

monitoring:
  hosts:
    localhost_monitoring:
      start_services: false
      ansible_connection: local
      name: test-node

probe:
  hosts:
    localhost_probe:
      start_services: false
      ansible_connection: local
      zone: test

tailscale:
  hosts:
    localhost_tailscale:
      start_services: false
      ansible_connection: local
      name: test-node
