---
- name: Install tailscale dependencies
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Add Tailscale GPG apt Key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    state: present

- name: Add Tailscale Repository
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/ubuntu jammy main
    state: present

- name: Update apt and install Tailscale
  ansible.builtin.apt:
    pkg:
      - tailscale
    state: present
    update_cache: true

- name: Make Tailscale conf
  ansible.builtin.copy:
    src: 99-tailscale.conf
    dest: /etc/sysctl.d/99-tailscale.conf
    mode: "0644"
