---
- name: Install tailscale dependencies
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
    state: latest
    update_cache: true

- name: Add Tailscale GPG apt Key
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    state: present

- name: Add Tailscale Repository
  apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/ubuntu jammy main
    state: present

- name: Update apt and install Tailscale
  apt:
    pkg:
      - tailscale
    state: present
    update_cache: true

- name: make Tailscale conf
  copy:
    src: 99-tailscale.conf
    dest: /etc/sysctl.d/99-tailscale.conf
