---
- name: Install common tools dependencies
  ansible.builtin.apt:
    pkg:
      - bat
      - curl
      - exa
      - git
      - htop
      - lm-sensors
      - fd-find
      - powertop
      - ripgrep
      - tmux
      - unzip
      - vim
      - wget
      - zsh
    state: present
    update_cache: true

- name: Install deb releases
  ansible.builtin.include_tasks:
    file: deb.yml
  loop: "{{ common_internal.deb_releases | combine(common.deb_releases | default({}), recursive=True) | dict2items }}"

- name: Install tar releases
  ansible.builtin.include_tasks:
    file: tar.yml
  loop: "{{ common.tar_releases | dict2items }}"
  when: common.tar_releases is defined

- name: Rust
  ansible.builtin.import_tasks:
    file: rust.yml
