---
- name: "Check if installed"
  ansible.builtin.stat:
    path: /usr/local/bin/{{ item.value.name }}
  register: "check_bin"
  changed_when: "not check_bin.stat.exists"

- name: Make scratch dir
  ansible.builtin.file:
    dest: "/tmp/{{ item.key }}"
    state: directory
    mode: "0775"
  when: "not check_bin.stat.exists"

- name: "Download"
  ansible.builtin.get_url:
    url: "{{ item.value.release }}"
    dest: "/tmp/{{ item.key }}/{{ item.value.file }}"
    mode: "0644"
  when: "not check_bin.stat.exists"

- name: "Extract"
  ansible.builtin.unarchive:
    src: "/tmp/{{ item.key }}/{{ item.value.file }}"
    dest: "/tmp/{{ item.key }}"
  when: "not check_bin.stat.exists"

- name: Install to /usr/local/bin/
  ansible.builtin.shell: "chmod +x {{ item.value.target }} && mv {{ item.value.target }} /usr/local/bin/{{ item.value.name }}"
  args:
    chdir: "/tmp/{{ item.key }}"
    creates: /usr/local/bin/{{ item.value.name }}
  when: "not check_bin.stat.exists"

- name: Cleanup scratch dir
  ansible.builtin.file:
    dest: "/tmp/{{ item.key }}"
    state: absent
  when: "not check_bin.stat.exists"
