resource_types:
  - name: slack-alert
    type: registry-image
    source:
      repository: arbourd/concourse-slack-alert-resource

# common flags we want to set on all jobs
job-common-settings: &job-common
  build_log_retention:
    days: 2
    builds: 20
    minimum_succeeded_builds: 1
  on_success:
    put: notify
    params:
      alert_type: success
  on_failure:
    put: notify
    params:
      alert_type: failed
  on_abort:
    put: notify
    params:
      alert_type: aborted
  on_error:
    put: notify
    params:
      alert_type: errored

resources:
  - name: homelab-ansible
    type: git
    icon: github
    source:
      uri: git@github.com:mattcl/homelab-ansible.git
      private_key: ((github.private-key))
      ignore_paths:
        - "README.md"
        - ".dockerignore"
        - "docker-compose.yaml"
        - "justfile"
        - "docker/*"

  # we separate these so that we don't always trigger the image build when we
  # push to the repo
  - name: homelab-ansible-docker
    type: git
    icon: github
    source:
      uri: git@github.com:mattcl/homelab-ansible.git
      private_key: ((github.private-key))
      branch: master
      paths:
        - "docker/*"

  - name: ubuntu-22.04
    type: registry-image
    icon: docker
    source:
      repository: mattcl/ansible-ci
      tag: "22.04"
      username: ((dockerhub.user))
      password: ((dockerhub.token))

  - name: nightly-trigger
    type: time
    icon: alarm
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/Los_Angeles
      initial_version: true

  - name: notify
    type: slack-alert
    icon: slack
    source:
      url: ((slack.webhook-url))
      channel: ((slack.channel))
      concourse_url: ((server.url))

jobs:
  - name: build-ubuntu-22.04
    <<: *job-common
    plan:
      - get: homelab-ansible-docker
        trigger: true

      - task: build
        privileged: true
        tags:
          - internal
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: homelab-ansible-docker
          outputs:
            - name: image
          params:
            DOCKERFILE: homelab-ansible-docker/docker/ubuntu-22.04.Dockerfile
          run:
            path: build

      - put: ubuntu-22.04
        params:
          image: image/image.tar

  - name: lint-and-test
    <<: *job-common
    plan:
      - in_parallel:
        - get: homelab-ansible
          trigger: true
        - get: ubuntu-22.04
          trigger: false
          passed:
            - build-ubuntu-22.04

      - task: lint
        tags:
          - internal
        image: ubuntu-22.04
        file: homelab-ansible/ci/lint.yaml
        input_mapping:
          repo: homelab-ansible

  - name: converge-build_node
    <<: *job-common
    plan:
      - in_parallel:
        - get: homelab-ansible
          trigger: true
          passed:
            - lint-and-test
        - get: ubuntu-22.04
          trigger: false
          passed:
            - lint-and-test
        - get: nightly-trigger
          trigger: true

      - task: converge
        tags:
          - internal
        image: ubuntu-22.04
        file: homelab-ansible/ci/converge.yaml
        input_mapping:
          repo: homelab-ansible
        params:
          CREATE_USER: matt
          PLAYBOOK: build_node.yml
          VAULT_PASSWORD: ((vault-password))

  - name: converge-dev_box
    <<: *job-common
    plan:
      - in_parallel:
        - get: homelab-ansible
          trigger: true
          passed:
            - lint-and-test
        - get: ubuntu-22.04
          trigger: false
          passed:
            - lint-and-test
        - get: nightly-trigger
          trigger: true

      - task: converge
        tags:
          - internal
          - ser6
        image: ubuntu-22.04
        file: homelab-ansible/ci/converge.yaml
        input_mapping:
          repo: homelab-ansible
        params:
          CREATE_USER: matt
          PLAYBOOK: dev_box.yml
          VAULT_PASSWORD: ((vault-password))
        # the various installation tools like chezmoi and asdf are kind of flaky
        attempts: 2
        timeout: 15m

  - name: converge-monitoring
    <<: *job-common
    plan:
      - in_parallel:
        - get: homelab-ansible
          trigger: true
          passed:
            - lint-and-test
        - get: ubuntu-22.04
          trigger: false
          passed:
            - lint-and-test
        - get: nightly-trigger
          trigger: true

      - task: converge
        tags:
          - internal
        image: ubuntu-22.04
        file: homelab-ansible/ci/converge.yaml
        input_mapping:
          repo: homelab-ansible
        params:
          CREATE_USER: matt
          PLAYBOOK: monitoring.yml
          VAULT_PASSWORD: ((vault-password))

  - name: converge-tailscale
    <<: *job-common
    plan:
      - in_parallel:
        - get: homelab-ansible
          trigger: true
          passed:
            - lint-and-test
        - get: ubuntu-22.04
          trigger: false
          passed:
            - lint-and-test
        - get: nightly-trigger
          trigger: true

      - task: converge
        tags:
          - internal
        image: ubuntu-22.04
        file: homelab-ansible/ci/converge.yaml
        input_mapping:
          repo: homelab-ansible
        params:
          CREATE_USER: matt
          PLAYBOOK: tailscale.yml
          VAULT_PASSWORD: ((vault-password))
