---
- name: Set dev user home
  ansible.builtin.set_fact:
    dev_home: "/home/{{ dev_user }}"

- name: Install docker dependencies
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Update apt and install docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Add dev_user to docker group
  ansible.builtin.user:
    name: "{{ dev_user }}"
    groups: docker
    append: true

- name: Restrict docker default subnets
  ansible.builtin.template:
    src: daemon.json
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: "0644"
    force: false
