---
- name: Set dev user home
  ansible.builtin.set_fact:
    dev_home: "/home/{{ dev_user }}"

- name: Create key dir
  ansible.builtin.file:
    dest: /opt/concourse/keys
    state: directory
    mode: "0775"

- name: Create tsa_host_key file
  ansible.builtin.copy:
    src: keys/tsa_host_key.pub
    dest: /opt/concourse/keys/tsa_host_key.pub
    mode: "0644"
    decrypt: true
    force: false

- name: Create worker_key file
  ansible.builtin.copy:
    src: keys/worker_key
    dest: /opt/concourse/keys/worker_key
    mode: "0644"
    decrypt: true
    force: false

- name: Create service dir
  ansible.builtin.file:
    dest: "{{ dev_home }}/services/concourse-worker"
    state: directory
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: "0775"

- name: Create compose file
  ansible.builtin.template:
    src: docker-compose.yaml
    dest: "{{ dev_home }}/services/concourse-worker/docker-compose.yaml"
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: "0644"
    force: false
