---
common_internal:
  apt_packages:
    - bat
    - curl
    - exa
    - git
    - htop
    - jq
    - lm-sensors
    - fd-find
    - powertop
    - ripgrep
    - tmux
    - unzip
    - vim
    - wget
    - zsh

  deb_releases:
    dust:
      name: "du-dust"
      release: "https://github.com/bootandy/dust/releases/download/v0.8.6/du-dust_0.8.6_amd64.deb"
      file: "du-dust_0.8.6_amd64.deb"
