---
- name: Check for chezmoi
  ansible.builtin.stat:
    path: "{{ dev_home }}/bin/chezmoi"
  register: chezmoi_status

- name: Download chezmoi installer
  ansible.builtin.get_url:
    url: "https://get.chezmoi.io/lb"
    dest: "/tmp/install-chezmoi"
    mode: '0755'
  when: not chezmoi_status.stat.exists

- name: Install chezmoi
  ansible.builtin.command:
    cmd: "/tmp/install-chezmoi -b {{ dev_home }}/bin"
    creates: "{{ dev_home }}/bin/chezmoi"
  when: not chezmoi_status.stat.exists

# there's no great way to convey a password age as an argument, so we're just
# going to put the decrypted key where we expect it to be
- name: Add decrypted key
  ansible.builtin.copy:
    src: key.txt
    dest: "{{ dev_home }}/key.txt"
    mode: "0600"
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    decrypt: true
    force: false

- name: Apply dotfiles
  ansible.builtin.command:
    cmd: >
      "{{ dev_home }}/bin/chezmoi" init
      --apply {{ dotfiles.repo.https_url }}
    creates: "{{ dev_home }}/.local/share/chezmoi"
  when: not chezmoi_status.stat.exists

- name: Change dotfile origin url
  ansible.builtin.command:  # noqa: command-instead-of-module
    cmd: git remote set-url origin {{ dotfiles.repo.ssh_url }}
    chdir: "{{ dev_home }}/.local/share/chezmoi"
  changed_when: true
  when: not chezmoi_status.stat.exists
