---
- name: Checkout fzf
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ dev_home }}/.fzf"
    version: "{{ fzf.version }}"
    depth: 1

- name: Install fzf
  ansible.builtin.command:
    cmd: "{{ dev_home }}/.fzf/install"
    creates: "{{ dev_home }}/.fzf/bin/fzf"
