---
- name: Set dev user home
  ansible.builtin.set_fact:
    dev_home: "/home/{{ dev_user }}"

- name: Make home bin dir
  ansible.builtin.file:
    dest: "{{ dev_home }}/bin"
    state: directory
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: "0775"

- name: Make home bin dir
  ansible.builtin.file:
    dest: "{{ dev_home }}/.local/share"
    state: directory
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: "0775"

- name: Run oh-my-zsh tasks
  ansible.builtin.import_tasks: ohmyzsh.yml

- name: Run fzf tasks
  ansible.builtin.import_tasks: fzf.yml

- name: Run dotfiles tasks
  ansible.builtin.import_tasks: dotfiles.yml

- name: Run python tasks
  ansible.builtin.import_tasks: python.yml

- name: Run asdf tasks
  ansible.builtin.import_tasks: asdf.yml

- name: Run nvim tasks
  ansible.builtin.import_tasks: nvim.yml
