---
- name: Make home bin dir
  ansible.builtin.file:
    dest: /home/matt/bin
    state: directory
    owner: matt
    group: matt
    mode: "0775"

- name: Make home bin dir
  ansible.builtin.file:
    dest: /home/matt/.local/share
    state: directory
    owner: matt
    group: matt
    mode: "0775"

- name: Run oh-my-zsh tasks
  ansible.builtin.import_tasks: ohmyzsh.yml

- name: Run fzf tasks
  ansible.builtin.import_tasks: fzf.yml

- name: Run dotfiles tasks
  ansible.builtin.import_tasks: dotfiles.yml

- name: Run python tasks
  ansible.builtin.import_tasks: python.yml

- name: Run nvim tasks
  ansible.builtin.import_tasks: nvim.yml
