---
dev_user: matt

common:
  apt_packages:
    - build-essential
    - direnv
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - python3
    - python3-pip
    - shellcheck
    - tk-dev
    - xz-utils
    - zlib1g-dev

  deb_releases:
    cargo_watch:
      name: "cargo-watch"
      release: "https://github.com/watchexec/cargo-watch/releases/download/v8.4.0/cargo-watch-v8.4.0-x86_64-unknown-linux-gnu.deb"
      file: "cargo-watch-v8.4.0-x86_64-unknown-linux-gnu.deb"

    git_delta:
      name: "git-delta"
      release: "https://github.com/dandavison/delta/releases/download/0.16.5/git-delta_0.16.5_amd64.deb"
      file: "git-delta_0.16.5_amd64.deb"

    hyperfine:
      name: "hyperfine"
      release: "https://github.com/sharkdp/hyperfine/releases/download/v1.17.0/hyperfine-musl_1.17.0_amd64.deb"
      file: "hyperfine-musl_1.17.0_amd64.deb"

  tar_releases:
    just:
      name: "just"
      release: "https://github.com/casey/just/releases/download/1.14.0/just-1.14.0-x86_64-unknown-linux-musl.tar.gz"
      file: "just-1.14.0-x86_64-unknown-linux-musl.tar.gz"
      target: "just"

    k_nine_s:
      name: "k9s"
      release: "https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz"
      file: "k9s_Linux_amd64.tar.gz"
      target: "k9s"

    kubeseal:
      name: "kubeseal"
      release: "https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.23.0/kubeseal-0.23.0-linux-amd64.tar.gz"
      file: "kubeseal-0.23.0-linux-amd64.tar.gz"
      target: "kubeseal"

    kustomize:
      name: "kustomize"
      release: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.1.0/kustomize_v5.1.0_linux_amd64.tar.gz"
      file: "kustomize_v5.1.0_linux_amd64.tar.gz"
      target: "kustomize"

    lazydocker:
      name: "lazydocker"
      release: "https://github.com/jesseduffield/lazydocker/releases/download/v0.20.0/lazydocker_0.20.0_Linux_x86.tar.gz"
      file: "lazydocker_0.20.0_Linux_x86.tar.gz"
      target: "lazydocker"

    navi:
      name: "navi"
      release: "https://github.com/denisidoro/navi/releases/download/v2.22.1/navi-v2.22.1-x86_64-unknown-linux-musl.tar.gz"
      file: "navi-v2.22.1-x86_64-unknown-linux-musl.tar.gz"
      target: "navi"

    tokei:
      name: "tokei"
      release: "https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-x86_64-unknown-linux-musl.tar.gz"
      file: "tokei-x86_64-unknown-linux-musl.tar.gz"
      target: "tokei"

python_versions:
  - "3.10.11"

# if this gets changed, it'll require updating the zshenv for the nvim venv as
# well
pyenv_global: "3.10.11"

# we have to indicate the created bin, as not all packages map directy to bin
# name(s)
pipx_packages:
  black:
    bin: black
  cookiecutter:
    bin: cookiecutter
  poetry:
    bin: poetry
